### ISSUE TITLE
Russian translation for "hydration"

### ISSUE THREAD

**Issue by shadow-identity** [sveltejs-translations/content-server#23]
Hi and thank you for your work!
In Russian we translate "hydration" to "гидратация", but in this documentation we have also "гидрация" (and this is the most popular translation in the docs).
I suppose to leave only one translation for consistency, and to use "гидратация" because this is an existing translation of "hydration" term.

**Comment by AlexxNB** [comment]
Literally `hydraton` translate in to `гидрация` as a physical process. But `гитратация` is commonly used for `web hydration`. Also I found that [Oracle](https://docs.oracle.com/cloud/help/ru/content-cloud/CECCE/GUID-2F1C725E-5823-4C9B-B4AE-C23530E87EBD.htm) and [Google](https://developers.google.com/web/updates/2019/02/rendering-on-the-web?hl=ru) use `гитратация` in their docs. So I agree that we need use only this term.

**Comment by shadow-identity** [comment]
I made a fix

**Comment by AlexxNB** [comment]
Cool, thanks!
